# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 175d2f66047c140cd692b8503acd252052878f923d47accf61d2ad0663fbacc24ef571a2b9c16302ce1f7e965523be2006765c38b9566fc2a6a548faaffca4ba

test:
  secret_key_base: ac7898bd0cd5bd72e1768c7216209cfd9b6391927634bd05fbd96b5e798f1652539d626e2781afb40c2134488dec6b8577dcb225842544cbc169fef66a8ef5e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
